Automate database migrations with Flyway
Bean-Bank-Coin/bean-bank-coin pull request #2
Opened 2024-03-03 20:58 UTC by bryce-bbd

## Changes
- flyway config file
- flyway workflow file
- migrations folder for sql

2024-03-05 08:01 UTC, KatlegoKungoane requested changes
Why is the terraform stuff in the flyway branch

2024-03-05 08:26 UTC, bryce-bbd commented
Because I branched from the terraform branch. Once the terraform pull request is merged I'll merge main into this flyway branch and the diff changes will only show the flyway stuff

2024-03-10 13:43 UTC, bryce-bbd reviewed
Resolved

2024-03-10 21:52 UTC, VerushanNaidoo approved these changes

2024-03-11 07:09 UTC, KatlegoKungoane approved these changes

2024-03-11 07:20 UTC, merged